"use client";

import {
  LayoutDashboard,
  Wallet,
  Target,
  BarChart3,
  Users,
  Settings,
  LogOut,
  Plus,
  Pause,
  Play,
  Eye,
  Edit,
  Trash2,
  Download,
  Upload,
  Search,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Filter,
  RefreshCw,
  Check,
  AlertCircle,
  Info,
  TrendingUp,
  TrendingDown,
  Image,
  Video,
  ExternalLink,
  Sun,
  Moon,
  MoreHorizontal,
  Bell,
  Mail,
  Phone,
  MapPin,
  Globe,
  CreditCard,
  Lock,
  Unlock,
  Clock,
  Calendar,
  FileText,
  Folder,
  FolderPlus,
  Link,
  Copy,
  Share2,
  Heart,
  HeartOff,
  Star,
  Flag,
  Archive,
  Send,
  Paperclip,
  Smile,
  Meh,
  Frown,
  HelpCircle,
  Minus,
  PlusCircle,
  XCircle,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  ArrowDownCircle,
  ArrowLeftCircle,
  ArrowRightCircle,
  CheckCircle,
} from "lucide-react";

export const Icons = {
  Dashboard: LayoutDashboard,
  Wallet: Wallet,
  Campaign: Target,
  Reports: BarChart3,
  Users: Users,
  Settings: Settings,
  Logout: LogOut,
  Plus: Plus,
  Pause: Pause,
  Play: Play,
  Eye: Eye,
  Edit: Edit,
  Trash: Trash2,
  Download: Download,
  Upload: Upload,
  Search: Search,
  Menu: Menu,
  Close: X,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  Filter: Filter,
  Refresh: RefreshCw,
  Check: Check,
  AlertCircle: AlertCircle,
  Info: Info,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  Image: Image,
  Video: Video,
  ExternalLink: ExternalLink,
  Sun: Sun,
  Moon: Moon,
  MoreHorizontal: MoreHorizontal,
  Bell: Bell,
  Mail: Mail,
  Phone: Phone,
  MapPin: MapPin,
  Globe: Globe,
  CreditCard: CreditCard,
  Lock: Lock,
  Unlock: Unlock,
  Clock: Clock,
  Calendar: Calendar,
  FileText: FileText,
  Folder: Folder,
  FolderPlus: FolderPlus,
  Link: Link,
  Copy: Copy,
  Share: Share2,
  Heart: Heart,
  HeartOff: HeartOff,
  Star: Star,
  Flag: Flag,
  Archive: Archive,
  Send: Send,
  Paperclip: Paperclip,
  Smile: Smile,
  Meh: Meh,
  Frown: Frown,
  Help: HelpCircle,
  Minus: Minus,
  PlusCircle: PlusCircle,
  XCircle: XCircle,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  ArrowUpCircle: ArrowUpCircle,
  ArrowDownCircle: ArrowDownCircle,
  ArrowLeftCircle: ArrowLeftCircle,
  ArrowRightCircle: ArrowRightCircle,
  CheckCircle: CheckCircle,
};

export type IconNames = keyof typeof Icons;
